### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by matthijs2704** [HarshilShah/DeckTransition#1]
Hey!
Matt from WWDCSCholars here :) 

You sent me this library a few days ago. It looks neat! But we were wondering, could you please add Carthage support so we can actually implement it in the app, without too much hassle?

**Comment by HarshilShah** [comment]
Hi there!

I just pushed a new [`carthage-test`](https://github.com/HarshilShah/DeckTransition/tree/carthage-test) branch. I have never used Carthage — I followed [this guide](https://medium.com/@filippotosetto/how-to-create-a-carthage-framework-8d9d65f98ac2) to make the branch — so please take a look and let me know if it’s done correctly or if any changes are needed.

**Comment by matthijs2704** [comment]
Don't think this will work? I took a look at the branch and you have only changed the Example, but not the library itself ;)

**Comment by HarshilShah** [comment]
I just added a new scheme for the library and made it shared; haven’t touched the example at all

Haven’t used it yet, but I made a new project, added `github “HarshilShah/DeckTransition” “carthage-test”` to the Cartfile and it seems to build the framework just ok. Could you give that a shot?

**Comment by matthijs2704** [comment]
Huh it actually works! I also know why, Carthage finds the xcworkspace created by CocoaPods in the example folder and builds the library through the example xcode workspace 😉  So it works, but it doesn't deserve a beauty award 😛 

Thanks!

**Comment by matthijs2704** [comment]
Actually I'll leave this issue open so it can be changed to a seperate xcode project later instead of this quick 'n dirty fix :)

**Comment by HarshilShah** [comment]
Hmm, that’s a weird hack from CocoaPods, dunno why the default template sets it up this way.

**Comment by txaiwieser** [comment]
How its going this Carthage integration? :)

**Comment by HarshilShah** [comment]
The branch works currently, although the entire xcworkspace is downloaded and compiled. Any idea if simply adding a top-level xcodeproj will fix that?

**Comment by HarshilShah** [comment]
Fixed in #23
