### ISSUE TITLE
CPU Hiccup when present panel

### ISSUE THREAD

**Issue by purepure** [harshilshah/DeckTransition#111]
Hi!
Your lib is amazing, I am working with its in my project. Thank for this!
there is lack of some configuration to make this lib blend in much better for many app but the most importance thing is the CPU consumption when I present the panel. This hiccup take about 16%-32% depend of each case but 16% is too much high for this presenting.
Do I miss something?

<img width="344" alt="Screen Shot 2019-09-03 at 00 11 34" src="https://user-images.githubusercontent.com/3175469/64128247-c64f5600-cddf-11e9-9d6d-3e6d212c1447.png">

**Comment by HarshilShah** [comment]
Hi there, thanks for filing an issue. Could you please upload a project based on the Example app included within the library that reproduces the behaviour you’re seeing, and also the conditions and versions (OS, device, etc.) you’re seeing the error in?

**Comment by purepure** [comment]
Hi @HarshilShah !
by comparing between "push" and "present" I recognize this is NOT your library issue, it is my code. The hiccup happens because I have a massive viewcontroller (tone of layout constrains update at the init time).
I am sorry to take your time. Close this for now

Thank you so much

**Comment by HarshilShah** [comment]
Good to know, hope your issue gets fixed!
