### ISSUE TITLE
I want to show Image on Top then TextView next to Image View with margin 20.

### ISSUE THREAD

**Issue by imobdev-nucitrus** [HarshilShah/DeckTransition#3]
How do I achieve this?

**Comment by imobdev-nucitrus** [comment]
I got the solution.

I added Image into TextView using `UITextView` property `textView.textStorage.insert`.

Thanks for this nice library.

**Comment by HarshilShah** [comment]
Glad you could solve your issue. 👍🏽

Hope you get some value from using the library!
