### ISSUE TITLE
Presenting View Controller on Modal View Controller removes deck effect

### ISSUE THREAD

**Issue by mergesort** [HarshilShah/DeckTransition#34]
After presenting a modal view controller on a view controller that was presented using `DeckTransition`, the deck effect goes away.

## How to reproduce

Take the example project, and add this code to `viewDidLoad()` in `ModalViewController`.

```swift
DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(1)) {
    let safariViewController = SFSafariViewController(url: URL(string: "https://www.google.com")!)
    self.present(safariViewController, animated: true, completion: nil)
}
```

## Result

Before:
![before](https://user-images.githubusercontent.com/716513/30039099-8b394770-919a-11e7-8c3d-9242a8140185.png)

During presentation:
![presented](https://user-images.githubusercontent.com/716513/30039100-92c66ce8-919a-11e7-9f42-5cd7afb5a7b2.png)

After dismissal:
![after](https://user-images.githubusercontent.com/716513/30039103-95568344-919a-11e7-992a-6334fc2a6043.png)

You can see in the last image that the rounded corners and inset is now gone.

Thank you for the hard work. Please let me know if there's any more information I can provide!

**Comment by HarshilShah** [comment]
I thought this was some sort of complicated issue with `UIPresentationController` at first. Turns out it was, but a simple one. Fixed in 1.0.3. Thanks for the detailed repro steps + code!
