### ISSUE TITLE
StatusBar appearance doesn't change using storyboards...

### ISSUE THREAD

**Issue by BaranEm** [HarshilShah/DeckTransition#37]
In your example file you are creating an object of `ModalViewController` and present this view controller via `present(_:animated:completion:)` after `transitioningDelegate` and `modalPresentationStyle` are set. This works as expected. The statusBar appearance changes with the transition from `default` to `lightContent` and then back to `default` again when dismissing.

But creating a storyboard segue by following the instructions in your `README` file (line 51) and perform the segue by invoking `performSegue(withIdentifier:sender)` doesn't change the statusBar appearance as expected. It keeps its `default` value. I couldn't figure out why. 

Tested on Xcode 9GM simulator with iOS 11, iPhone 7+8.

**Comment by HarshilShah** [comment]
Status bar changes are outside the control of this library; the actual change is performed directly by UIKit’s stock transition logic.

If you’re not seeing the status bar colour change, it probably has to do with whether you’ve set `modalPresentationCapturesStatusBarAppearance` to true in your modal VC

If not that, it’s probably an issue with your containment setup and forwarding appearance proxies. Regardless, both are outside of this library’s actual purview

**Comment by BaranEm** [comment]
`modalPresentationCapturesStatusBarAppearance` is set true by default as you know. Setting it `false` doesn't change the behavior. 

And you might be right. I have the same issue with my own library too. Thought I did something wrong in the implementation and used yours.

**Comment by HarshilShah** [comment]
Ah okay, I thought the problem you were describing was with using it in your own view hierarchy. Does using a segue break status bar changing within the demo app as well?

**Comment by BaranEm** [comment]
Yes, I just tested it using your example demo project and didn't change anything except I added a `UIViewController` with the identifier `ModalViewController` and a segue to `Main.storyboard`.

**Comment by HarshilShah** [comment]
Hmm, thanks, I’ll take a look

**Comment by HarshilShah** [comment]
Removed the tap gesture in the `ViewController` and replaced the manual transition with a Storyboard segue and it's working just fine here. Could you upload your modified version where you can reproduce the bug?

Here's what the segue looks like for me. Works the same as manual presentation

<img width="260" alt="screen shot 2017-09-18 at 6 14 21 pm" src="https://user-images.githubusercontent.com/3503595/30542471-2796895e-9c9d-11e7-926d-a199497b8b32.png">

**Comment by HarshilShah** [comment]
Gah, hit close by mistake, apologies

**Comment by BaranEm** [comment]
I did replace the manual transition with a Storyboard segue like you said, but still not working. Strange.

Just hit run and you should see that the statusBar appearance is not changing. The only modification are made to the root `ViewController` and Storyboard. 
[DeckTransition-master-statusbar-issue.zip](https://github.com/HarshilShah/DeckTransition/files/1310719/DeckTransition-master-statusbar-issue.zip)

**Comment by HarshilShah** [comment]
You’re not transitioning to the ModalViewController. It’s just a random normal UIViewController
