### ISSUE TITLE
Opening a new modal on top breaks the layout

### ISSUE THREAD

**Issue by LucasAdam** [HarshilShah/DeckTransition#4]
Hey, first of all great library ! It really does just what I need so thank you.

However for one of my use case I have to open another modal on top of the one the lib is already presenting. I've made a small [Video](http://winz.ovh/shared/bug.mov) so you can see the issue but basicaly once you close the new modal, the 28px offset is now at the bottom and not a the top and my layout is quite weird (see the bottom blue stuff)

**Comment by HarshilShah** [comment]
Hi there, thanks for the heads up on the issue. I'm not sure at first glance what's causing this issue, but I'll take a look into it. I'll add a comment when I find something; please do the same if you find anything as well. Also, thanks for the video, it certainly helps!

**Comment by yakubov** [comment]
Hello! I got the same problem when i presented UIImagePicker in modal view on the top of controller presented by DeckTranstion.
I resolve this issue by setting imagePicker.modalPresentationStyle = .overFullScreen

**Comment by CTKRocks** [comment]
I have the same problem. I solved it very simply by changing the other modals to use the DeckTransition. I know it's not the best solution, but it worked.

**Comment by HarshilShah** [comment]
So there's not much discussion available about `UIPresentationController`, but as best as I can tell from the few threads and some conversations I've had with folks, presentation controllers aren't notified when a VC is presented or dismissed. This seems to be out of my hands for now. Feel free to let me know if you do find any relevant information, though

**Comment by HarshilShah** [comment]
Turns out this was an easy fix after all. Fixed in 1.0.3
