### ISSUE TITLE
Performing appearanceTransition in animation controllers can leave presenting controller in invalid state

### ISSUE THREAD

**Issue by robinkunde** [HarshilShah/DeckTransition#40]
I don't believe calling beginAppearanceTransition/endAppearanceTransition in DeckDismissingAnimationController/DeckPresentingAnimationController is the right approach. I've discovered the following problems:

1) If the modal presented or dismissed without animation, the methods will not be called.
2) If animation calls are unbalanced (ie. present with animation, dismiss without), the presenting controller will be left in an invalid state, where it will not receive any appearance calls at all moving forward, despite still being visible.

I tested two possible solutions:
1) Remove the calls entirely, and instead have DeckPresentationController override shouldRemovePresentersView and return true. Downside is that it would likely interfere with refresh the snapshot.
2) Make these calls in *transitionWillBegin/*transitionDidEnd instead. This worked just as well in my testing, but I'm not sure at which point inside these methods would be the best place, so I didn't include a PR.

**Comment by HarshilShah** [comment]
Thanks for this bug report, and especially listing out solutions you've tried! I'm going with the second approach and I've moved the methods to the `DeckPresentationController`. This will be fixed in the next update

**Comment by mergesort** [comment]
As of 1.3.4, I'm still seeing this error happening.

```swift
`Unbalanced calls to begin/end appearance transitions for <UINavigationController: 0x7fd1c2033400>`,
```

It seems relatively benign, but I figured it was worth mentioning.

**Comment by HarshilShah** [comment]
Thanks! I've removed the methods entirely, so it's back to pre-1.3.0 levels, and all the error reports I've received have been after that, so hopefully it shouldn't happy again.
