### ISSUE TITLE
Use transition to present another view controller on custom presented controller

### ISSUE THREAD

**Issue by sammygutierrez** [HarshilShah/DeckTransition#41]
At the moment, when the transition is used to present a view controller on top of another view controller that already has been presented with the transition, the layout breaks.

![deck-doublemodal](https://user-images.githubusercontent.com/2582590/31155390-782268de-a873-11e7-9e56-f0f1d85d5c79.gif)

<img width="743" alt="blackbg" src="https://user-images.githubusercontent.com/2582590/31155710-cab7e54a-a875-11e7-93c4-fac0f18b6d01.png">

I want to achieve something similar to the [Overcast app](https://itunes.apple.com/us/app/overcast/id888422857?mt=8) where another view controller can be presented (the second view controller is shown in the back right on top of the first one).

![overcast_modal](https://user-images.githubusercontent.com/2582590/31155393-7caa51b4-a873-11e7-807e-cdb8468ed815.gif)

I want to implement this but I'd like to see if anyone has any advice on the best way to accomplish this. The black `backgroundView` is hiding what's behind it. Would I need a whole new custom transition class?

**Comment by HarshilShah** [comment]
The library was never intended to be used for multiple such segues, and at least in my testing way back before I even open sourced it, there were some issues with detecting whether the underlying VC was also presented with Deck. 

It's definitely doable, however would require changing quite a lot of code. There are a bunch of transforms etc. that depend on the presenting VC's initial frame before presentation and final frame after dismissal being the fullscreen view, so the change would really be nontrivial.

Thanks for bringing this up, I'll look into it more

**Comment by HarshilShah** [comment]
So I have a PR up for this: #43 

Please try this and let me know if you run into any weird issues. Thanks!
