### ISSUE TITLE
Rounded corner of presenting view controller does not animate alongside dismissal

### ISSUE THREAD

**Issue by MilanNosal** [HarshilShah/DeckTransition#42]
Rounded corner of the presenting view controller seems to be set back to the original quite abruptly (which does not seem to happen in the gif presented on the intro screen). Is there a way to configure this? Or is this by design?

I've gone through the code shortly, but it does not seem that it is supposed to be animated (it seems that rounded corners are rendered using this RoundedView but it did not seem that it was animated).

**Comment by HarshilShah** [comment]
The GIF was made with the initial release, where the rounding was done on the entire presenting view. Over time I ended up rewriting how that works, and the current implementation, while way more performant, indeed does not animate the corner radius. This will be fixed in a future release

**Comment by HarshilShah** [comment]
This is fixed in 1.3.3
