### ISSUE TITLE
Is there a way to use it in swift 3?

### ISSUE THREAD

**Issue by Ashkan-Sarlak** [HarshilShah/DeckTransition#46]
Hey man, thanks for the library, though I still can't get it working.
I know you've mentioned swift 4 as a requirement, but I thought maybe the previous versions would work on swift 3. Is it possible? What is the version I should enter in pod file?

When I set a segue to custom and class to DeckSegue, I get this error:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not create a segue of class '(null)''

**Comment by HarshilShah** [comment]
Hi there, version 1.3.4 was the last version to run on Swift 3. Apologies for not noting this in the changelog, I'll be updating it soon. Thanks for the bug report

**Comment by Ashkan-Sarlak** [comment]
Thanks for quick response. In version 1.3.4 I get 4 errors in the library, which are:

.../Pods/DeckTransition/Source/DeckPresentationController.swift:54:45: Use of undeclared type 'NSKeyValueObservation' (2 times)
.../Pods/DeckTransition/Source/DeckPresentationController.swift:353:75: Invalid character in source file (2 times)

I think NSKeyValueObservation class is available only in swift 4.

**Comment by HarshilShah** [comment]
Gah, sorry. 1.3.4 is the first version to support Swift 4; 1.3.3 should work

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
