### ISSUE TITLE
Snapshot does not properly display when presented from a SearchController

### ISSUE THREAD

**Issue by zmknox** [HarshilShah/DeckTransition#51]
While working on What's Open with @SRCT, we noticed when adding search to our app that the snapshot generated by DeckTransition just generates black when presented from a SearchController.

Here's an example: https://streamable.com/b3bcv

And here's how we're calling to present from our main view to the detail view with DeckTransition:
```
let destDelegate = DeckTransitioningDelegate()
destination.modalPresentationStyle = .custom
destination.transitioningDelegate = destDelegate

// present the detail view over the search controller if we're searching
if searchController.isActive {
    searchController.present(destination, animated: true, completion: nil)
}
else {
    present(destination, animated: true, completion: nil)
}
```
(The full code can be found at https://git.gmu.edu/srct/whats-open-ios ).

It is very possible that we're doing something wrong, but for the life of me I don't know what that may be.

**Comment by HarshilShah** [comment]
Hey there, thanks for the bug report, and especially the video.

I can't find any Deck code in the `master` branch of that repo, could you link me to the branch/file where you're seeing the issue?

My best guess without having looked at the code so far would be it's an issue with [`definesPresentationContext`](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621456-definespresentationcontext). I haven't heard of anyone having issues related to that with Deck, but I've run across it in other projects/with other transitions. Might wanna try messing with the value for that for various controllers in your view hierarchy.

I ran a Google search for `definesPresentationContext` to link you to the docs page, and the very second result was for a similar problem as yours, solved by setting that variable: [UISearchController causes black screen Swift 2.0](https://stackoverflow.com/questions/33291347/uisearchcontroller-causes-black-screen-swift-2-0). Let me know if this helps

**Comment by zmknox** [comment]
Thanks for the reply! I’ll look into that!

We’re still in active development so our UI is in some branches. I believe you’ll find DeckTransition in the `superfluousness` branch and search added in the `issue25-addingSearchFeature` branch.

**Comment by zmknox** [comment]
Looks like your suspicions were correct! Adding `self.definesPresentationContext = true` to my ViewController's `viewDidLoad()` did the trick! Thanks!

It might be worth noting it as a troubleshooting step in the readme, as I never would have thought about setting that property myself.

**Comment by HarshilShah** [comment]
Glad it's fixed! Will note this in the (TBD) FAQ
