### ISSUE TITLE
Top of long UIAlertView action sheet cropped

### ISSUE THREAD

**Issue by barackbrobama** [HarshilShah/DeckTransition#52]
When presenting an alert view action sheet within the deck view, long lists result in the top of the alert being cropped off.

Short list appearance:
![screenshot 2017-12-05 03 29 25](https://user-images.githubusercontent.com/3849277/33563666-ac850576-d96c-11e7-9aa1-ce7f526d3e35.png)

Long list appearance:
![screenshot 2017-12-05 03 30 11](https://user-images.githubusercontent.com/3849277/33563701-be15f354-d96c-11e7-8343-49080310f78f.png)

**Comment by HarshilShah** [comment]
That's just what action sheets look like when you have more items than can fit onscreen. Not related to Deck at all
