### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by otymartin** [HarshilShah/DeckTransition#53]
@HarshilShah 
I love but library. Would love to have the option to use it without a top-offset at all on any device.

I just it for the UX which flows better than presenting a modal and i like the swipe to dismiss gesture along with the scaling of the presenting VC.

So if you could add the option for zero Y offset, that would be cool!

**Comment by HarshilShah** [comment]
Hi there, glad you like the library.

I'm happy to show you how you can add the feature (just [modifying this one variable](https://github.com/HarshilShah/DeckTransition/blob/master/Source/DeckPresentationController.swift#L109) to be 0 should be enough, I think). Unfortunately I won't be able to add this to the main source, for the time being at least.

The goal of this library is simply to replicate the card style modal, and while it appears quite simple, there are a host of moving parts. You can see the `DeckPresentationController` file to see for yourself.

It is incredible difficult to automate the testing animations, and as such most of the "testing" is just me with a bunch of simulators opened with slow motion enabled running the animation multiple times, in multiple different configurations, to check for any regressions. Any customisation points introduce not just the expectancy that they won't be removed, but that they'll keep working, adding quite a bit more testing workload. As such, I offer precisely zero customisations as of now.

Maybe in the future I can find a way to expose more settings while retaining testability, but for now, I won't be able to offer this, sorry.

**Comment by otymartin** [comment]
Thanks @HarshilShah I appreciate the response.
I took your advice and did it manually.
