### ISSUE TITLE
Breaking main view controller animation

### ISSUE THREAD

**Issue by alexandergmacleod** [HarshilShah/DeckTransition#55]
I have been attempting to modify the animation transition as I believe the current implementation is too harsh a transition. I have replaced the code inside animateTransition() of DeckPresentingAnimationController to:

        let convenienceAnimator = UIViewPropertyAnimator(duration: transitionDuration(using: transitionContext), dampingRatio: 1.5) {
            presentedViewController.view.frame = finalFrameForPresentedView
        }
            
        convenienceAnimator.addCompletion({ position in
            transitionContext.completeTransition(position == .end)
        })
            
        convenienceAnimator.startAnimation()

Now the presentedViewController appears much more smoothly to my liking. However, this seems to break the transition of the previous view controller moving backwards - it now just snaps back. How would I solve this issue?

**Comment by HarshilShah** [comment]
I've only briefly tried UIViewPropertyAnimator for a custom transition (different from Deck), and have run into similar weird issues there as well. Can't really help you here, sorry.
