### ISSUE TITLE
DeckTransition - update storyboard documentation

### ISSUE THREAD

**Issue by g30r93g** [HarshilShah/DeckTransition#60]
Hi there.

Really want to use DeckTransition but it isn't working for me.
I'm using a dark background and an embedded UIView with a tap gesture recogniser.

Please can you help me.

**Comment by g30r93g** [comment]
Here are some screenshots of my code.
![screen shot 2018-02-14 at 00 46 35](https://user-images.githubusercontent.com/31825917/36182250-99d7b856-1120-11e8-9b12-fc9aa314b530.png)
![screen shot 2018-02-14 at 00 46 48](https://user-images.githubusercontent.com/31825917/36182253-9d68f016-1120-11e8-9309-57ba3825c441.png)

**Comment by HarshilShah** [comment]
What exactly do you mean by "DeckTransition not working"? What's not working here?

**Comment by g30r93g** [comment]
Those lines of code are from your example app which works. However, when I want to present it in my app, it will just push back the OrderViewController. It doesn't display the LargeOrderViewController

**Comment by HarshilShah** [comment]
Could you post screenshots of what you're seeing when you call `present` with and without the `DeckTransitioningDelegate`?

**Comment by g30r93g** [comment]
I've got it. Needed to conform a segue to DeckSegue. Couldn't find it in the docs so please update for others!

**Comment by HarshilShah** [comment]
Glad the issue is solved. It's already covered in the docs fwiw

**Comment by HarshilShah** [comment]
Renamed this to make searching easier.
