### ISSUE TITLE
What if i dont want to use background transition?

### ISSUE THREAD

**Issue by nitingohel** [HarshilShah/DeckTransition#61]
First of all thank you very much to making such a wonderful source for developers. I use that for single screen present look like following:

![screen shot 2018-02-15 at 12 49 28 pm](https://user-images.githubusercontent.com/5137595/36245045-122018d8-124f-11e8-8c67-6b14812d15d9.png)

But i want to use stack background viewcontroller stay at their position just look black overlay without gose to depth. like following screenshot:

![screen shot 2018-02-15 at 12 49 08 pm](https://user-images.githubusercontent.com/5137595/36245059-2a189e74-124f-11e8-9f9c-870abb0521fe.png)

Can you let me know how do i stock transit for background viewcontrollre that stop go to depth.

**Comment by HarshilShah** [comment]
Sorry, but this is not a supported feature, and there are no plans to add it. The goal of this library is just to recreate the iOS card transition so I’m sticking to it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
