### ISSUE TITLE
White area opens up at the top while dismissing

### ISSUE THREAD

**Issue by gbuela** [HarshilShah/DeckTransition#69]
Hi! I'm trying it out on a UITableViewController. This is the table shown from the top position:
![simulator screen shot - iphone 7 plus - 2018-04-01 at 18 14 47](https://user-images.githubusercontent.com/19420015/38177485-ddcb789a-35d8-11e8-995d-a2b45e7ef5d2.png)

And this is how it looks when it is being dismissed. As you swipe down, this white area opens up and gradually grows before the modal is dismissed. Do you know what it is and how I can avoid it?
![simulator screen shot - iphone 7 plus - 2018-04-01 at 18 14 45](https://user-images.githubusercontent.com/19420015/38177486-dfc3ab68-35d8-11e8-9310-407b3567d114.png)

Thanks

**Comment by HarshilShah** [comment]
Hi there, thanks for the bug report.

This issue has been fixed in #64 and the fix will be included in the next release. Until then, you could just use the `master` branch of this repo which contains the fix already.
