### ISSUE TITLE
How to disable the "deck" mode for further controllers?

### ISSUE THREAD

**Issue by janczakb** [HarshilShah/DeckTransition#80]
I need to open the controller in "deck" mode - it works.
Next I need to open another but not as a "deck"

**Comment by HarshilShah** [comment]
The Deck mode only happens when you explicitly set the transitioningDelegate to be the DeckTransitioningDelegate. Other view controllers will present without the Deck style

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
