### ISSUE TITLE
Graphic glitch when a "full screen" view controller over the Deck Transition View is dismissed.

### ISSUE THREAD

**Issue by MehdiBrandoMahdloo** [HarshilShah/DeckTransition#81]
I have this small issue but i'd love to get rid of it if possible.
I have the Deck Transition View working properly, but If I open a "full screen" view controller over it (presented with Pop Up), when I dismiss this view controller the top side of the Deck Transition "bounces" before recalculate its height.

It seems like the Deck Transition is going "full screen" with no rounded corners, and then when it recalculates its height, it "bounce" down and restore the rounded corners. 

To recreate this behaviour, just present a "full screen" view controller over the Deck Transition.

Is there a way to fix this? 
Thank you.

**Comment by HarshilShah** [comment]
Hi there, this has been addressed in #4. You can fix this by changing the `modalPresentationStyle` of the view controller you want to present on top of the Deck modal

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
