### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by AndreaMiotto** [HarshilShah/DeckTransition#86]
Hi, is there any plan to migrate to swift 4.2?

**Comment by HarshilShah** [comment]
Hi there,

I’m gonna have a 4.2 branch up soon, merged to master with the Xcode GM, with more updates coming later.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by HarshilShah** [comment]
Swift 4.2 support is on master as of v2.1.0
