### ISSUE TITLE
How to dismiss the presented Model view by clicking on some button ?

### ISSUE THREAD

**Issue by Mohammed-Eliass** [HarshilShah/DeckTransition#9]
I was wondering if I could dismiss the presented Model  view by clicking on button like cancel button ?

**Comment by anmolmalhotra** [comment]
Have you tried this on IBAction of Cancel button:

`delegate.isDismissEnabled = true`

**Comment by Mohammed-Eliass** [comment]
Absolutely, but nothing happened.
I meant what to do after this to dismiss the Model ?
