### ISSUE TITLE
Lags first time, second time works

### ISSUE THREAD

**Issue by phiren** [HarshilShah/DeckTransition#96]
First time, background view moves to back without animation, second time it works.

**Comment by phiren** [comment]
Problem was related with textview making first responder in viewDidLoad method.

When it present view controller B from View controller A, it does not show animation of moving back view controller A, it moves back but without animation. in View controller B, there is text view, which become first responder whenever open view controller B. So now moved code from viewDidLoad to viewDidAppear, and it works fine now.

**Comment by HarshilShah** [comment]
Closing this issue as it seems to be resolved.
